<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FLIGHTS</name>
   <tag></tag>
   <elementGuidId>96024b62-5ecb-4b2e-b965-defe063fcff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='content']/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://test-katrina.icore.studio/users/auth?user_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOjE3NiwidXNlcl9uYW1lIjoia2F0cmluYV9zeXN0ZW1AaWNvcmUuc3R1ZGlvIiwidXNlcl9maXJzdF9uYW1lIjoiS2F0cmluYSIsInVzZXJfbGFzdF9uYW1lIjoiU3lzdGVtIiwidXNlcl9kZXNjcmlwdGlvbiI6IlJvb3QgU3lzdGVtICIsInVzZXJfaXNfYWN0aXZlIjoxLCJ1c2VyX2VtYWlsIjoia2F0cmluYV9zeXN0ZW1AaWNvcmUuc3R1ZGlvIiwidXNlcl9yZWxhdGVkX2tleSI6bnVsbCwidXNlcl9tb2JpbGUiOiIiLCJ1c2VyX3Nzb19tYXBfaWQiOm51bGx9LCJpYXQiOjE1NzA1ODg2OTUsImp0aSI6ImQ4NGMxNDQwLWVhM2QtMTFlOS1iZTY3LTBiMDEyNjAwYTBiOCJ9.5QmZh-ud8aJtr37PvYeg67C9eNxnV1M5DX8NllHh5P4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FLIGHTS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;search-box-wrapper&quot;]/div[@class=&quot;search-box container&quot;]/ul[@class=&quot;search-tabs clearfix&quot;]/li[1]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//section[@id='content']/div/div/ul/li/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <value>//a[contains(text(),'FLIGHTS')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRAINS'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOTELS'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>(//a[@href='http://test-katrina.icore.studio/users/auth?user_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOjE3NiwidXNlcl9uYW1lIjoia2F0cmluYV9zeXN0ZW1AaWNvcmUuc3R1ZGlvIiwidXNlcl9maXJzdF9uYW1lIjoiS2F0cmluYSIsInVzZXJfbGFzdF9uYW1lIjoiU3lzdGVtIiwidXNlcl9kZXNjcmlwdGlvbiI6IlJvb3QgU3lzdGVtICIsInVzZXJfaXNfYWN0aXZlIjoxLCJ1c2VyX2VtYWlsIjoia2F0cmluYV9zeXN0ZW1AaWNvcmUuc3R1ZGlvIiwidXNlcl9yZWxhdGVkX2tleSI6bnVsbCwidXNlcl9tb2JpbGUiOiIiLCJ1c2VyX3Nzb19tYXBfaWQiOm51bGx9LCJpYXQiOjE1NzA1ODg2OTUsImp0aSI6ImQ4NGMxNDQwLWVhM2QtMTFlOS1iZTY3LTBiMDEyNjAwYTBiOCJ9.5QmZh-ud8aJtr37PvYeg67C9eNxnV1M5DX8NllHh5P4'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//section/div/div/ul/li/a</value>
   </webElementXpaths>
</WebElementEntity>
